In [46]:
import numpy as np
import theano
import theano.tensor as tt
import hky
from importlib import reload
reload(hky)

from hky import *

In [64]:
Pt = hky_transition_probs(1.0, 2.0, np.ones(4)/4, 1).eval()
Pt

array([[0.3953989 , 0.17226874, 0.21616618, 0.21616618],
       [0.17226874, 0.3953989 , 0.21616618, 0.21616618],
       [0.21616618, 0.21616618, 0.3953989 , 0.17226874],
       [0.21616618, 0.21616618, 0.17226874, 0.3953989 ]])

In [22]:
x, y = np.array([1, 0]), np.array([2, 2])
Pt[x, y].eval()

array([0.86466472, 0.86466472])

In [38]:
Pt_expm = hky_transition_probs_expm(1.0, 2.0, np.ones(4)/4, 1).eval()
Pt_expm

array([[0.3953989 , 0.17226874, 0.21616618, 0.21616618],
       [0.17226874, 0.3953989 , 0.21616618, 0.21616618],
       [0.21616618, 0.21616618, 0.3953989 , 0.17226874],
       [0.21616618, 0.21616618, 0.17226874, 0.3953989 ]])

In [63]:
alpha = tt.scalar('alpha')
beta = tt.scalar('beta')
pi = tt.vector('pi')
t = tt.scalar('t')
Pt_sum = hky_transition_probs_expm(alpha, beta, pi, t).sum()
grad_node = tt.grad(Pt_sum, alpha)
grad_func = theano.function([alpha, beta, pi, t], grad_node)
grad_func(1.0, 2.0, np.ones(4)/4, 1)

array(-2.77555756e-17)